### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ninsignares** [Displayr/rhtmlLabeledScatter#177] opened 2020-06-10 16:09 UTC
Hi team!
I am trying to update this package in my develop environment, but it returns error:
I type: 
`install_github("Displayr/rhtmlLabeledScatter", force = TRUE, build = TRUE)`

and it returns:

```
ERROR
   copying to build directory failed
Error: Failed to install 'rhtmlLabeledScatter' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problema al copiar .\Displayr-rhtmlLabeledScatter-1b343aa\theSrc\test\snapshots\local\master\testPlans\functionalTest_old\functionalTest_old data.functionalTest.bubbleplot_simple_no_label_field-snap.png  a C:\Users\NELSON~1.INS\AppData\Local\Temp\Rtmp2jkaEZ\Rbuild200c3922143f\Displayr-rhtmlLabeledScatter-1b343aa\theSrc\test\snapshots\local\master\testPlans\functionalTest_old\functionalTest_old data.functionalTest.bubbleplot_simple_no_label_field-snap.png: No such file or directory
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problema al copiar .\Displayr-rhtmlLabeledScatter-1b343aa\theSrc\test\snapshots\local\master\testPlans\functionalTest_old\functionalTest_old data.functionalTest.scatterplot_simple_no_label_field-snap.png
```

I use RStudio 1.3.959 and R 4.0.1 over Windows 10 Pro

**Comment by LuciaPelliccia** [comment] 2020-07-10 16:21
Hi @ninsignares,
I encountering the same problem during the installation of the package flipMultivariates, which includes the rhtmlLabeledScatter package as a dependency. 
I tried with the R version 3.6.1 and with 4.0.2 but I ended up with the same problem:

![err2](https://user-images.githubusercontent.com/67955716/87176253-23f2df80-c2da-11ea-9016-2190650387e3.png)


Have you solved the problem?

PS: I asked my collegue to install it and it works on his system. 
(Windows 10 Pro, R 4.0.2) 

Thanks in advance. 
​​​​

**Comment by ninsignares** [comment] 2020-07-10 16:41
Hi @LuciaPelliccia.
I solved the problem by running R as administrator. I tried package installation on my personal Mac and it ran smoothly, so I came back to my job laptop and run R as administrator, with a user outside corporate domain and it ran just perfect.

I strongly recommend to install all Displayr packages from a R Gui launched from an administrator user.

I have to say, in advance, that I always install R in a D:\R folder, so all users that have access to my laptop can use it. So if you are not administrator and you has not installed your R version in a folder outside your user environment, this solution may fail, because packages will be installed in the admin user personal folder. However, give it a try and come back with news about it.

If you can become an administrator for your pc, the best solution could be ask for it.

Stay safe!

Nelson

**Comment by JustinCCYap** [comment] 2021-10-21 04:48
Closing issue as this appears to have been caused by a space character in a test file name which has been fixed. The package now installs OK on Windows.

**Closed as completed by JustinCCYap** 2021-10-21 04:48 UTC
